# Generated by scripts/update_channels.py; edit shared installation rules in flycast.rb.
cask "flycast@master" do
  version "2026.09.10.092808,0abac3465dc9547dca5f30f3352fee10b67e34b2"
  sha256 "9dea15902eaeced16906730e50d24d52fdd4c4151fceb52dc681f815be5f7d65"

  url "https://flycast-builds.s3.fr-par.scw.cloud/osx/heads/master-#{version.csv.second}/flycast.app.zip"
  name "Flycast (Master)"
  desc "Dreamcast, Naomi, Naomi 2 and Atomiswave emulator (master builds)"
  homepage "https://github.com/flyinghead/flycast"

  livecheck do
    skip "Updated from upstream CI by scripts/update_channels.py"
  end

  depends_on :macos

  if ::Version.new(HOMEBREW_VERSION) < ::Version.new("6.0.13")
    raise "Flycast requires Homebrew 6.0.13 or newer. Run `brew update`, then retry installation."
  end

  app "Flycast.app"

  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{appdir}}/Flycast.app"]
  end

  # Keep saves, BIOS files and user-created controller mappings. Additional
  # macOS instances store their configuration in numbered subdirectories.
  zap trash: [
        "~/.flycast/[0-9]*/emu.cfg",
        "~/.flycast/emu.cfg",
        "~/Library/Application Support/Flycast/[0-9]*/emu.cfg",
        "~/Library/Application Support/Flycast/emu.cfg",
      ],
      rmdir: [
        "~/.flycast",
        "~/Library/Application Support/Flycast",
      ]
end
