# Generated by scripts/update_channels.py; edit shared installation rules in flycast.rb.
cask "flycast@master" do
  version "2026.10.07.115232,0d9853df9a917eba2f7a84158bd1c3bccb8933e8"
  sha256 "88063f4baeee5944366ca0e1fa4b1b385908537e4fbe110035c19f61c35420db"

  url "https://flycast-builds.s3.fr-par.scw.cloud/osx/heads/master-#{version.csv.second}/flycast.app.zip"
  name "Flycast (Master)"
  desc "Dreamcast, Naomi, Naomi 2 and Atomiswave emulator (master builds)"
  homepage "https://github.com/flyinghead/flycast"

  livecheck do
    skip "Updated from upstream CI by scripts/update_channels.py"
  end

  depends_on :macos

  if ::Version.new(HOMEBREW_VERSION) < ::Version.new("6.0.13")
    raise "Flycast requires Homebrew 6.0.13 or newer. Run `brew update`, then retry installation."
  end

  app "Flycast.app"

  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{appdir}}/Flycast.app"]
  end

  # Keep saves, BIOS files and user-created controller mappings. Additional
  # macOS instances store their configuration in numbered subdirectories.
  zap trash: [
        "~/.flycast/[0-9]*/emu.cfg",
        "~/.flycast/emu.cfg",
        "~/Library/Application Support/Flycast/[0-9]*/emu.cfg",
        "~/Library/Application Support/Flycast/emu.cfg",
      ],
      rmdir: [
        "~/.flycast",
        "~/Library/Application Support/Flycast",
      ]
end
