# Generated by scripts/update_channels.py; edit shared installation rules in flycast.rb.
cask "flycast@dev" do
  version "2026.09.22.135332,0a304f1396bd1b743f34b33ea3e64753eb195f02"
  sha256 "93839f7edcf8f67b9f89cd979cc590e1a6e706c6e7e96239b71ed79be8bfb9f9"

  url "https://flycast-builds.s3.fr-par.scw.cloud/osx/heads/dev-#{version.csv.second}/flycast.app.zip"
  name "Flycast (Dev)"
  desc "Dreamcast, Naomi, Naomi 2 and Atomiswave emulator (dev builds)"
  homepage "https://github.com/flyinghead/flycast"

  livecheck do
    skip "Updated from upstream CI by scripts/update_channels.py"
  end

  depends_on :macos

  if ::Version.new(HOMEBREW_VERSION) < ::Version.new("6.0.13")
    raise "Flycast requires Homebrew 6.0.13 or newer. Run `brew update`, then retry installation."
  end

  app "Flycast.app"

  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{appdir}}/Flycast.app"]
  end

  # Keep saves, BIOS files and user-created controller mappings. Additional
  # macOS instances store their configuration in numbered subdirectories.
  zap trash: [
        "~/.flycast/[0-9]*/emu.cfg",
        "~/.flycast/emu.cfg",
        "~/Library/Application Support/Flycast/[0-9]*/emu.cfg",
        "~/Library/Application Support/Flycast/emu.cfg",
      ],
      rmdir: [
        "~/.flycast",
        "~/Library/Application Support/Flycast",
      ]
end
