# Generated by scripts/update_channels.py; edit shared installation rules in flycast.rb.
cask "flycast@dev" do
  version "2026.10.04.105859,552a86086b038f71f997e563ae9e4100e09ee0c7"
  sha256 "89e6b48c052a51149f808e1a6489bc8a0ed525ce1cd1a028ae975c2cb4d81534"

  url "https://flycast-builds.s3.fr-par.scw.cloud/osx/heads/dev-#{version.csv.second}/flycast.app.zip"
  name "Flycast (Dev)"
  desc "Dreamcast, Naomi, Naomi 2 and Atomiswave emulator (dev builds)"
  homepage "https://github.com/flyinghead/flycast"

  livecheck do
    skip "Updated from upstream CI by scripts/update_channels.py"
  end

  depends_on :macos

  if ::Version.new(HOMEBREW_VERSION) < ::Version.new("6.0.13")
    raise "Flycast requires Homebrew 6.0.13 or newer. Run `brew update`, then retry installation."
  end

  app "Flycast.app"

  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{appdir}}/Flycast.app"]
  end

  # Keep saves, BIOS files and user-created controller mappings. Additional
  # macOS instances store their configuration in numbered subdirectories.
  zap trash: [
        "~/.flycast/[0-9]*/emu.cfg",
        "~/.flycast/emu.cfg",
        "~/Library/Application Support/Flycast/[0-9]*/emu.cfg",
        "~/Library/Application Support/Flycast/emu.cfg",
      ],
      rmdir: [
        "~/.flycast",
        "~/Library/Application Support/Flycast",
      ]
end
