#!/usr/bin/env python3
"""Pin stable/master/dev casks to published macOS builds; never commit or push."""

import argparse
from dataclasses import dataclass
from datetime import datetime, timezone
import hashlib
import io
import json
from pathlib import Path
import plistlib
import re
from urllib.parse import urlencode
from urllib.request import Request, urlopen
import xml.etree.ElementTree as ET
import zipfile


BUCKET = "https://flycast-builds.s3.fr-par.scw.cloud/"
LATEST_RELEASE = "https://api.github.com/repos/flyinghead/flycast/releases/latest"
CHANNELS = ("master", "dev")
KEY_PATTERN = re.compile(r"osx/heads/(master|dev)-([0-9a-f]{40})/flycast\.app\.zip")
NS = {"s": "http://s3.amazonaws.com/doc/2006-03-01/"}
ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class Build:
    channel: str
    commit: str
    key: str
    modified: datetime
    size: int

    @property
    def version(self):
        return f"{self.modified:%Y.%m.%d.%H%M%S},{self.commit}"


def fetch(url):
    request = Request(url, headers={"User-Agent": "homebrew-flycast-channel-updater"})
    with urlopen(request, timeout=60) as response:
        return response.read()


def list_builds(fetch_url=fetch):
    """Read all pages; the bucket's lexical order is not chronological."""
    builds = []
    token = None
    seen_tokens = set()
    while True:
        query = {"list-type": "2", "prefix": "osx/heads/"}
        if token:
            query["continuation-token"] = token
        page = ET.fromstring(fetch_url(BUCKET + "?" + urlencode(query)))
        for entry in page.findall("s:Contents", NS):
            key = entry.findtext("s:Key", namespaces=NS) or ""
            match = KEY_PATTERN.fullmatch(key)
            if not match:
                continue
            size = int(entry.findtext("s:Size", namespaces=NS) or "0")
            if size <= 0:
                continue
            timestamp = entry.findtext("s:LastModified", namespaces=NS)
            modified = datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
            if modified.tzinfo is None:
                raise ValueError(f"Missing timezone for {key}")
            builds.append(Build(*match.groups(), key, modified.astimezone(timezone.utc), size))
        if page.findtext("s:IsTruncated", namespaces=NS) == "false":
            return builds
        token = page.findtext("s:NextContinuationToken", namespaces=NS)
        if not token or token in seen_tokens:
            raise ValueError("Incomplete or looping bucket pagination")
        seen_tokens.add(token)


def latest_builds(builds):
    latest = {}
    for channel in CHANNELS:
        candidates = [build for build in builds if build.channel == channel]
        if not candidates:
            raise ValueError(f"No published macOS build for {channel}")
        latest[channel] = max(candidates, key=lambda build: (build.modified, build.commit))
    return latest


def archive_sha(build, payload):
    """Check bundle identity against the artifact key before updating its hash."""
    if len(payload) != build.size:
        raise ValueError(f"Download size mismatch for {build.channel}")
    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        info = plistlib.loads(archive.read("Flycast.app/Contents/Info.plist"))
        commit = info.get("CFBundleVersion", "")
        if not re.fullmatch(r"[0-9a-f]{7,40}", commit) or not build.commit.startswith(commit):
            raise ValueError(f"Bundle commit mismatch for {build.channel}: {commit!r}")
        if info.get("CFBundleIdentifier") != "com.flyinghead.Flycast":
            raise ValueError(f"Unexpected bundle identifier for {build.channel}")
        archive.getinfo("Flycast.app/Contents/MacOS/Flycast")
    return hashlib.sha256(payload).hexdigest()


def render_cask(build, sha, stable_source):
    # Generated casks stay self-contained and share stable's installation/zap rules.
    common = stable_source[stable_source.index("  depends_on :macos\n"):]
    return f'''# Generated by scripts/update_channels.py; edit shared installation rules in flycast.rb.
cask "flycast@{build.channel}" do
  version "{build.version}"
  sha256 "{sha}"

  url "{BUCKET}osx/heads/{build.channel}-#{{version.csv.second}}/flycast.app.zip"
  name "Flycast ({build.channel.capitalize()})"
  desc "Dreamcast, Naomi, Naomi 2 and Atomiswave emulator ({build.channel} builds)"
  homepage "https://github.com/flyinghead/flycast"

  livecheck do
    skip "Updated from upstream CI by scripts/update_channels.py"
  end

{common}'''


def update_stable_source(source, fetch_url=fetch):
    release = json.loads(fetch_url(LATEST_RELEASE))
    tag = release.get("tag_name", "")
    if release.get("draft") is not False or release.get("prerelease") is not False:
        raise ValueError("Expected a published stable release")
    if not re.fullmatch(r"v[0-9]+(?:\.[0-9]+)*", tag):
        raise ValueError(f"Unsupported stable release tag: {tag!r}")
    version = tag[1:]
    old_version = re.findall(r'^  version "([0-9]+(?:\.[0-9]+)*)"$', source, re.MULTILINE)
    old_sha = re.findall(r'^  sha256 "([0-9a-f]{64})"$', source, re.MULTILINE)
    if len(old_version) != 1 or len(old_sha) != 1:
        raise ValueError("Expected one stable version and checksum")
    old_parts = tuple(map(int, old_version[0].split(".")))
    new_parts = tuple(map(int, version.split(".")))
    width = max(len(old_parts), len(new_parts))
    if new_parts + (0,) * (width - len(new_parts)) < old_parts + (0,) * (width - len(old_parts)):
        raise ValueError("Refusing to move stable to an older release")

    name = f"flycast-macOS-{version}.zip"
    assets = [asset for asset in release.get("assets", []) if asset.get("name") == name]
    if len(assets) != 1 or assets[0].get("state") != "uploaded":
        raise ValueError(f"Expected one uploaded macOS release archive: {name}")
    asset = assets[0]
    url = f"https://github.com/flyinghead/flycast/releases/download/{tag}/{name}"
    if asset.get("browser_download_url") != url:
        raise ValueError("Unexpected stable archive URL")
    payload = fetch_url(url)
    if len(payload) != asset.get("size"):
        raise ValueError("Download size mismatch for stable")
    sha = hashlib.sha256(payload).hexdigest()
    if asset.get("digest") and asset["digest"] != f"sha256:{sha}":
        raise ValueError("Stable archive digest mismatch")
    if version == old_version[0] and sha != old_sha[0]:
        raise ValueError("Stable archive changed without a version change")
    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        info = plistlib.loads(archive.read("Flycast.app/Contents/Info.plist"))
        if info.get("CFBundleIdentifier") != "com.flyinghead.Flycast":
            raise ValueError("Unexpected bundle identifier for stable")
        if info.get("CFBundleShortVersionString") not in (version, tag):
            raise ValueError("Stable bundle version mismatch")
        archive.getinfo("Flycast.app/Contents/MacOS/Flycast")
    source = re.sub(r'^  version "[^"]+"$', f'  version "{version}"', source, count=1, flags=re.MULTILINE)
    return re.sub(r'^  sha256 "[^"]+"$', f'  sha256 "{sha}"', source, count=1, flags=re.MULTILINE)


def prepare_development_updates(root=ROOT, fetch_url=fetch, stable_source=None):
    stable = stable_source if stable_source is not None else (root / "Casks/flycast.rb").read_text()
    latest = latest_builds(list_builds(fetch_url))
    updates = {}
    # Validate both downloads before writing either cask.
    for channel, build in latest.items():
        path = root / f"Casks/flycast@{channel}.rb"
        old = path.read_text() if path.exists() else ""
        match = re.search(r'^  version "([^"]+)"$', old, re.MULTILINE)
        if match and match[1].split(",")[0] > build.version.split(",")[0]:
            raise ValueError(f"Refusing to move {channel} to an older build")
        sha = archive_sha(build, fetch_url(BUCKET + build.key))
        existing_sha = re.search(r'^  sha256 "([0-9a-f]{64})"$', old, re.MULTILINE)
        if match and match[1] == build.version and existing_sha and existing_sha[1] != sha:
            raise ValueError(f"Archive changed without a version change for {channel}")
        new = render_cask(build, sha, stable)
        if old != new:
            updates[path] = new
    return updates


def prepare_updates(root=ROOT, fetch_url=fetch):
    path = root / "Casks/flycast.rb"
    old = path.read_text()
    stable = update_stable_source(old, fetch_url)
    # Validate all three channels before returning any changes for writing.
    updates = prepare_development_updates(root, fetch_url, stable)
    if old != stable:
        updates[path] = stable
    return updates


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report pending updates without writing files")
    args = parser.parse_args()
    updates = prepare_updates()
    for path, content in updates.items():
        print(f"{'Would update' if args.check else 'Updating'} {path.relative_to(ROOT)}")
        if not args.check:
            path.write_text(content)
    if not updates:
        print("Stable, master, and dev casks are up to date")
    return 1 if args.check and updates else 0


if __name__ == "__main__":
    raise SystemExit(main())
